name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build plugin
      run: ./gradlew buildPlugin
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifact
        path: build/distributions/*.zip
        retention-days: 7
    
    - name: Verify plugin
      run: ./gradlew verifyPlugin